apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: serve-java-app
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
    # Param "task_type"
    # options: build/deploy/all
    - name: task_type
      value: "all"
    - name: target_cluster
      value: "C011b88fa"
    - name: app_name
      value: "sample-petclinic"
    - name: artifact_url
      value: "http://github.com/robertchoi80/sample-petclinic/spring-petclinic-2.7.0-SNAPSHOT.jar"
    - name: image_url
      value: "REGISTRY/IMAGE:TAG"
    - name: port
      value: "8080"
    #######################
    # Deploy-only params? #
    #######################
    # executable path in the image
    - name: executable_path
      value: "JAR_PATH_IN_THE_IMAGE"
    - name: profile
      value: "default"
    # Possible values: tiny, medium, large
    - name: resource_spec
      value: "medium"
    - name: tks_info_host
      value: ""

  templates:
  - name: main
    steps:
    - - name: build-image
        when: "{{workflow.parameters.task_type}} != 'deploy'"
        template: build-image
#    - - name: updateAsaStatusToTksInfo
#        templateRef:
#          name: update-asa-status
#          template: updateAsaStatus
#        arguments:
#          parameters:
#          - name: status
#            value: "BUILD_SUCCESS"
    - - name: deploy-app
        when: "{{workflow.parameters.task_type}} != 'build'"
        template: deploy-app
#    - - name: updateAsaStatusToTksInfo
#        templateRef:
#          name: update-asa-status
#          template: updateAsaStatus
#        arguments:
#          parameters:
#          - name: status
#            value: "DEPLOY_SUCCESS"

  #######################
  # Template Definition #
  #######################
  - name: build-image
    volumes:
    - name: varrun
      emptyDir: {}
    sidecars:
    - name: dind
      image: 'docker:20.10.16-dind'
      volumeMounts:
      - mountPath: /var/run
        name: varrun
      securityContext:
        privileged: true
    container:
      #TODO: split worker image
      image: 'sktcloud/appserving-worker:latest'
      volumeMounts:
      - mountPath: /var/run
        name: varrun
      env:
      - name: DOCKERHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: dockerhub-robert-token
            key: TOKEN
      command:
      - /bin/sh
      - '-exc'
      - |
        mkdir -p /apps && cd /apps/

        # TODO: How to pass auth info here?
        curl -L -o {{workflow.parameters.app_name}}.jar {{workflow.parameters.artifact_url}}

        # fetch Dockerfile & manifests from git
        git clone https://github.com/openinfradev/app-serve-template.git

        cp -r ./app-serve-template/Dockerfile .
        ls -l .

        ###############
        # Build Image #
        ###############

        # Replace port number in Dockerfile
        sed -i "s/JARFILENAME/{{workflow.parameters.app_name}}.jar/g" ./Dockerfile
        sed -i "s/PORTNUM/{{workflow.parameters.port}}/g" ./Dockerfile

        # Debug
        cat Dockerfile

        # Build docker image
        image_name="{{workflow.parameters.image_url}}"
        docker build -t $image_name .

        # Login to dockerhub
        docker login -u robertchoi80 -p $DOCKERHUB_TOKEN

        # Push image
        docker push $image_name

  - name: deploy-app
    #    outputs:
    #      parameters:
    #      - name: endpoint_url
    #        valueFrom:
    #          path: /apps/endpoint
    container:
      image: 'sktcloud/appserving-worker:latest'
      env:
      - name: DOCKERHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: dockerhub-robert-token
            key: TOKEN
      command:
      - /bin/sh
      - '-exc'
      - |
        mkdir -p /apps/

        # fetch manifests from git
        cd /apps
        git clone https://github.com/openinfradev/app-serve-template.git

        cp -r ./app-serve-template/* .
        ls -l .

        # Build manifest using kustomize
        kustomize build overlays/{{workflow.parameters.resource_spec}} > manifest.yaml

        # replace variable for the app
        image_name="{{workflow.parameters.image_url}}"
        sed -i "s#EXECUTABLE_PATH#{{workflow.parameters.executable_path}}#g" ./manifest.yaml
        sed -i "s/PORTNUM/{{workflow.parameters.port}}/g" ./manifest.yaml
        sed -i "s/APPNAME/{{workflow.parameters.app_name}}/g" ./manifest.yaml
        sed -i "s#IMAGEURL#${image_name}#g" ./manifest.yaml
        sed -i "s/PROFILE/{{workflow.parameters.profile}}/g" ./manifest.yaml

        # Debug
        cat manifest.yaml

        # Prepare kubeconfig
        KUBECONFIG_=$(kubectl get secret -n {{workflow.parameters.target_cluster}} {{workflow.parameters.target_cluster}}-kubeconfig -o jsonpath="{.data.value}" | base64 -d)
        if [[ -z "$KUBECONFIG_" ]]; then
          echo "Couldn't get kubeconfig for cluster {{workflow.parameters.target_cluster}}"
          exit 1
        fi

        echo "$KUBECONFIG_" > /etc/kubeconfig_temp
        export KUBECONFIG='/etc/kubeconfig_temp'

        # Deploy
        kubectl apply -f ./manifest.yaml -n {{workflow.parameters.app_name}}

        # Wait for pod to be ready
        kubectl wait --for=condition=Available --timeout=300s -n {{workflow.parameters.app_name}} deploy/{{workflow.parameters.app_name}}

        # Temporary output until app-serving service is implemented
        # This msg will be sent to CLI by app-serviing service.
        echo "The app <{{workflow.parameters.app_name}}> has been deployed successfully. Check the app endpoint as follows.

        # Endpoint
        $ kubectl get svc {{workflow.parameters.app_name}} -n {{workflow.parameters.app_name}} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
        # Port number
        $ kubectl get svc {{workflow.parameters.app_name}} -n {{workflow.parameters.app_name}} -o jsonpath='{.spec.ports[0].port}'"

        # For demo purpose only
        echo "Fetching app endpoint..."
        kubectl get svc {{workflow.parameters.app_name}} -n {{workflow.parameters.app_name}} -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' > /apps/endpoint
