apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-secrets
  namespace: argo
spec:
  templates:
  - name: deploySecrets
    activeDeadlineSeconds: 120
    inputs:
      parameters:
      - name: repo_url
        value: "" # Eg, "openinfradev/tks-admin-site"
      - name: secret_path
        value: "" # Eg, "directory/secret.yaml"
    container:
      image: k8s.gcr.io/hyperkube:v1.18.8
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -c
      - |
  
        git clone https://$(echo $gittoken|xargs)@{{input.parameters.repo_url}}
        repo_name=$(basename "{{input.parameters.repo_url}}")

        kubectl apply -f $repo_name/{{input.parameters.secret_path}}

        # TODO: need to add logic to check if the secret was successfully created?

      envFrom:
        - secretRef:
            name: "gittoken"
