apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: setup-sealed-secrets-infra
  namespace: argo
spec:
  entrypoint: process
  arguments:
    parameters:
    - name: site_name
      value: "hanu-reference"
    # TODO: This should be renamed to app_group_name
    - name: app_group
      value: "sealed-secrets"
    - name: manifest_repo_url
      value: "https://github.com/openinfradev/decapod-manifests"
    - name: revision
      value: "main"
## Uncomment following lines if you need to customize these ##
#    - name: master_key_repo_url
#      value: "github.com/openinfradev/tks-admin-site"
#    - name: master_key_secret_name
#      value: "github.com/openinfradev/tks-admin-site"
#    - name: sealed_secrets_repo_url
#      value: "github.com/openinfradev/tks-admin-site"
#      ...
##############################################################
  templates:
  - name: process
    steps:
    - - name: deployMasterKey
        templateRef:
          name: deploy-secrets
          template: deploySecrets
        argument:
          parameters:
          - name: repo_url
            value: "github.com/openinfradev/tks-admin-site"
          - name: secret_path
            value: "sealed-secret-key/master-key-secret.yaml"

    - - name: installControllers
        templateRef:
          name: tks-create-application
          template: installAppsOnAdmin
        arguments:
          parameters:
          - name: list
            value: |
              [
                 { "path": “sealed-secret-controller", "namespace": “kube-system” },
                 { "path": “kubed", "namespace": “kube-system” }
              ]

    - - name: deploySealedSecret
        templateRef:
          name: deploy-secrets
          template: deploySecrets
        argument:
          parameters:
          - name: repo_url
            value: "github.com/openinfradev/tks-admin-site"
          - name: secret_path
            value: "sealed-certificates/taco-cat-tls-sealed.yaml"
