apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: setup-sealed-secrets-on-usercluster
  namespace: argo
spec:
  entrypoint: process
  arguments:
    parameters:
    - name: git_account
      value: "tks-management"
    - name: contract_id
      value: "011b88fa-4d53-439f-9336-67845f994051"
    - name: cluster_id
      value: ""
    - name: app_group
      value: "sealed-secrets"
    - name: revision
      value: "main"
  templates:
  - name: process
    steps:
    - - name: deployMasterKey
        templateRef:
          name: deploy-secrets
          template: deploySecretsToUserCluster
        arguments:
          parameters:
          - name: repo_url
            value: "github.com/openinfradev/tks-admin-site"
          - name: secret_path
            value: "sealed-secret-key/master-key-secret.yaml"
          - name: kubeconfig_secret_name
            value: "{{workflow.parameters.cluster_id}}-kubeconfig"

    - - name: installControllers
        templateRef:
          name: tks-create-application
          template: installApps
        arguments:
          parameters:
          - name: list
            value: |
              [
                 { "path": "sealed-secret-controller", "namespace": "kube-system" },
                 { "path": "kubed", "namespace": "kube-system" }
              ]

    - - name: deploySealedSecret
        templateRef:
          name: deploy-secrets
          template: deploySecretsToUserCluster
        arguments:
          parameters:
          ##########################################################################
          # For real use case example 
          #- name: repo_url
          #  value: "github.com/tks-management/{{workflow.parameters.contract_id}}"
          #- name: secret_path
          #  value: "sealed-certificates/user-cat-tls-sealed.yaml"
          ##########################################################################
          - name: repo_url
            value: "github.com/openinfradev/tks-admin-site"
          - name: secret_path
            value: "sealed-certificates/taco-cat-tls-sealed.yaml"
          - name: kubeconfig_secret_name
            value: "{{workflow.parameters.cluster_id}}-kubeconfig"
