apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: setup-sealed-secrets-on-admincluster
  namespace: argo
spec:
  entrypoint: process
  arguments:
    parameters:
    # For create-application task #
    - name: manifest_repo_url
      value: "https://github.com/openinfradev/decapod-manifests"
    - name: site_name
      value: "decapod-reference"
    - name: app_prefix
      value: "{{=sprig.substr(0, 8, workflow.parameters.site_name)}}"
    - name: revision
      value: "main"
## Uncomment following lines and customize to fetch any secrets you want ##
#    - name: master_key_repo_url
#      value: "github.com/openinfradev/tks-admin-site"
#    - name: master_key_secret_name
#      value: "github.com/openinfradev/tks-admin-site"
#    - name: sealed_secrets_repo_url
#      value: "github.com/openinfradev/tks-admin-site"
#      ...
###########################################################################
  templates:
  - name: process
    steps:
    - - name: deployMasterKey
        templateRef:
          name: deploy-secrets
          template: deploySecretsToAdminCluster
        arguments:
          parameters:
          # In case of user cluster, repo url should be constructed from parameters
          # such as git_account, contract id & cluster id.
          - name: repo_url
            value: "github.com/openinfradev/tks-admin-site"
          - name: secret_path
            value: "sealed-secret-key/master-key-secret.yaml"
          - name: namespace
            value: kube-system

    - - name: installControllers
        templateRef:
          name: create-application
          template: installApps
        arguments:
          parameters:
          - name: list
            value: |
              [
                 { "app_group": "sealed-secrets", "path": "sealed-secrets-operator-crds", "namespace": "kube-system", "target_cluster": "tks-admin" },
                 { "app_group": "sealed-secrets", "path": "sealed-secrets-operator", "namespace": "kube-system", "target_cluster": "tks-admin" },
                 { "app_group": "sealed-secrets", "path": "kubed", "namespace": "kube-system", "target_cluster": "tks-admin" }
              ]

    - - name: deploySealedSecret
        templateRef:
          name: deploy-secrets
          template: deploySecretsToAdminCluster
        arguments:
          parameters:
          - name: repo_url
            value: "github.com/openinfradev/tks-admin-site"
          - name: secret_path
            value: "sealed-certificates/taco-cat-tls-sealed.yaml"
          - name: namespace
            value: default
