apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: aws-cluster-autoscaler-iam
  namespace: argo
spec:
  entrypoint: createIAMRole
  arguments:
    parameters:
    - name: cluster_id
      value: "Cc81dd656"

  volumes:
    - name: awsconfig
      secret:
        secretName: awsconfig-secret

  templates:
  - name: createIAMRole
    activeDeadlineSeconds: 1800
    container:
      image: harbor-cicd.taco-cat.xyz/tks/tks-aws:v1.0.0
      command:
      - /bin/bash
      - -exc
      - |
        mkdir ~/.aws
        cp /aws/* ~/.aws/

        echo "{
            \"Version\": \"2012-10-17\",
            \"Statement\": [
                {
                    \"Effect\": \"Allow\",
                    \"Action\": [
                        \"autoscaling:SetDesiredCapacity\",
                        \"autoscaling:TerminateInstanceInAutoScalingGroup\"
                    ],
                    \"Resource\": \"*\",
                    \"Condition\": {
                        \"StringEquals\": {
                            \"aws:ResourceTag/k8s.io/cluster-autoscaler/enabled\": \"true\",
                            \"aws:ResourceTag/k8s.io/cluster-autoscaler/$CLUSTER_ID\": \"owned\"
                        }
                    }
                },
                {
                    \"Effect\": \"Allow\",
                    \"Action\": [
                        \"autoscaling:DescribeAutoScalingInstances\",
                        \"autoscaling:DescribeAutoScalingGroups\",
                        \"autoscaling:DescribeScalingActivities\",
                        \"ec2:DescribeLaunchTemplateVersions\",
                        \"autoscaling:DescribeTags\",
                        \"autoscaling:DescribeLaunchConfigurations\",
                        \"ec2:DescribeInstanceTypes\"
                    ],
                    \"Resource\": \"*\"
                }
            ]
        }" > iam_policy.json
        aws iam create-policy --policy-name cluster-autoscaler-$CLUSTER_ID --policy-document file://iam_policy.json

        oidc_id=$(aws eks describe-cluster --name $CLUSTER_ID --query "cluster.identity.oidc.issuer" --output text | cut -d '/' -f 5)
        aws iam list-open-id-connect-providers | grep $oidc_id | cut -d "/" -f4
        eksctl utils associate-iam-oidc-provider --cluster $CLUSTER_ID --approve

        eksctl create iamserviceaccount \
          --name cluster-autoscaler \
          --namespace kube-system \
          --cluster $CLUSTER_ID
          --role-name "cluster-autoscaler-$CLUSTER_ID" \
          --attach-policy-arn arn:aws:iam::$ACCOUNT_ID:policy/cluster-autoscaler-$CLUSTER_ID \
          --override-existing-serviceaccounts \
          --approve

      env:
      - name: CLUSTER_ID
        value: "{{workflow.parameters.cluster_id}}"
      volumeMounts:
      - name: awsconfig
        mountPath: "/aws"

  - name: deleteIAMRole
    activeDeadlineSeconds: 1800
    container:
      image: harbor-cicd.taco-cat.xyz/tks/tks-aws:v1.0.0
      command:
      - /bin/bash
      - -exc
      - |
        mkdir ~/.aws
        cp /aws/* ~/.aws/
        eksctl delete iamserviceaccount --cluster $CLUSTER_ID --name cluster-autoscaler --namespace kube-system

      env:
      - name: CLUSTER_ID
        value: "{{workflow.parameters.cluster_id}}"
      volumeMounts:
      - name: awsconfig
        mountPath: "/aws"
