apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-tks-usercluster
  namespace: argo
spec:
  entrypoint: deploy
  arguments:
    parameters:
    - name: contract_id
      value: "0010010a-d6cb-459b-9148-1b02ac545753"
    - name: cluster_id
      value: "011b88fa-4d53-439f-9336-67845f994051"
    - name: template_name
      value: "template-std"
    - name: git_account
      value: "tks-management"
    - name: revision
      value: main
    - name: tks_admin
      value: "tks-admin"
    - name: app_group
      value: "tks-cluster"
    - name: tks_info_host
      value: "tks-info.tks.svc"

  volumes:
  - name: config
    secret:
      secretName: tks-admin-kubeconfig-secret
      namespace: argo
  - name: artifacts
    configMap:
      name: aws-artifacts
      namespace: argo
      defaultMode: 0555
  - name: tks-proto-vol
    configMap:
      name: tks-proto

  templates:
  - name: deploy
    steps:
    - - name: tks-create-cluster-site
        templateRef:
          name: tks-create-cluster-site
          template: main

    - - name: k8s-by-capi
        templateRef:
          name: tks-create-application-new
          template: installAppsOnAdmin
        arguments:
          parameters: 
          - name: list
            value: |
              [
                { "path": "cluster-api-aws", "namespace": "argo" }
              ]

    - - name: wait-for-clster-to-be-registered
        template: wait-for-cluster-registration

    - - name: install-cni-and-csi
        templateRef:
          name: tks-create-application-new
          template: installApps
        arguments:
          parameters: 
          - name: list
            value: |
              [
                { "path": "kubernetes-addons", "namespace": "taco-system" }
              ]

    - - name: update-cluster-status-to-running
        templateRef:
          name: update-tks-cluster-status
          template: updateClusterStatus
        arguments:
          parameters:
          - name: cluster_status
            value: RUNNING

  - name: wait-for-cluster-registration
    activeDeadlineSeconds: 1800
    container:
      image: ghcr.io/openinfradev/argocd-cli:v2.0.1
      command:
      - /bin/bash
      - -exc
      - |
        yes | ./argocd login --insecure $ARGO_SERVER --username $ARGO_USERNAME --password $ARGO_PASSWORD

        while [ $(./argocd cluster list | grep \ $target\ | wc -l ) == 0 ]; do
            echo "> Wait for cluster to be registered"
            sleep 1
        done
      envFrom:
      - secretRef:
          name: "decapod-argocd-config"
      env:
      - name: target
        value: "{{workflow.parameters.cluster_id}}"
