apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-cli
  namespace: argo
spec:
  arguments:
    parameters:
    - name: tks_api_url
      value: "http://tks-api.tks.svc:9110"
  templates:
  - name: login-tks-api
    container:
      name: login-tks-api
      image: harbor-cicd.taco-cat.xyz/tks/tks-e2e-test:test
      command:
        - /bin/bash
        - '-exc'
        - |
          tks login {{workflow.parameters.tks_api_url}} --organization-id master --account-id admin --password admin
          tks cluster list

  - name: create-usercluster
    inputs:
      parameters:
      - name: cluster_name
      - name: stack_template_id
      - name: organization_id
      - name: cloud_account_id
      - name: creator
      - name: description
    container:
      name: create-usercluster
      image: harbor-cicd.taco-cat.xyz/tks/tks-e2e-test:test
      command:
        - /bin/bash
        - '-exc'
        - |
          tks login {{workflow.parameters.tks_api_url}} --organization-id master --account-id admin --password admin

          CL_NAME="{{inputs.parameters.cluster_name}}"
          echo "* Create $CL_NAME cluster"
          tks cluster create ${CL_NAME} \
            --template "{{inputs.parameters.stack_template_id}}" \
            --organization-id "{{inputs.parameters.organization_id}}" \
            --cloud-setting-id "{{inputs.parameters.cloud_account_id}}" \
            --description "{{inputs.parameters.description}}" 

          threshold=30
          for i in $(seq 1 $threshold)
          do
            CL_STATUS=$(tks cluster list "{{inputs.parameters.organization_id}}" | grep $CL_NAME | awk '{ print $4 }')
            if [ "$CL_STATUS" = "RUNNING" ]; then
              break
            elif [ "$CL_STATUS" = "ERROR" ]; then
              exit 1
            fi

            if [ "$i" -ge "$threshold" ]; then
              echo "Timed out waiting for user-cluster to be ready."
              exit 1
            fi
            sleep 1m
          done

          tks cluster list "{{inputs.parameters.organization_id}}" | grep $CL_NAME | awk '{print $3}' | tee /mnt/out/cluster_id.txt
      volumeMounts:
        - name: out
          mountPath: /mnt/out
    volumes:
      - name: out
        emptyDir: { }
    outputs:
      parameters:
      - name: cluster-id
        valueFrom:
          default: "Something wrong"
          path: /mnt/out/cluster_id.txt

  - name: delete-usercluster
    inputs:
      parameters:
      - name: organization_id
      - name: cluster_id
    container:
      name: delete-usercluster
      image: harbor-cicd.taco-cat.xyz/tks/tks-e2e-test:test
      command:
        - /bin/bash
        - '-exc'
        - |
          tks login {{workflow.parameters.tks_api_url}} --organization-id master --account-id admin --password admin
          tks cluster delete {{inputs.parameters.cluster_id}}

          threshold=30
          for i in $(seq 1 $threshold)
          do
            CL_EXIST=$(tks cluster list -o "{{inputs.parameters.organization_id}}" | grep {{inputs.parameters.cluster_id}} | wc -l)
            if [ "$CL_EXIST" = "0" ]; then
              break
            fi

            CL_STATUS=$(tks cluster list -o "{{inputs.parameters.organization_id}}" | grep {{inputs.parameters.cluster_id}} | awk '{ print $3 }')
            if [ "$CL_STATUS" = "DELETED" ]; then
              break
            elif [ "$CL_STATUS" = "ERROR" ]; then
              exit 1
            fi

            if [ "$i" -ge "$threshold" ]; then
              echo "Timed out waiting for user-cluster to be deleted."
              exit 1
            fi
            sleep 1m
          done

  - name: create-service
    inputs:
      parameters:
      - name: cluster_id
      - name: name
      - name: type
      - name: creator
      - name: description
    container:
      name: create-service
      image: harbor-cicd.taco-cat.xyz/tks/tks-e2e-test:test
      command:
        - /bin/bash
        - '-exc'
        - |
          tks login {{workflow.parameters.tks_api_url}} --organization-id master --account-id admin --password admin
          tks appgroup create --name "{{inputs.parameters.name}}" --cluster-id "{{inputs.parameters.cluster_id}}" --type "{{inputs.parameters.type}}" --description "{{inputs.parameters.description}}"

          threshold=30
          for i in $(seq 1 $threshold)
          do
            SVC_STATUS=$(tks appgroup list {{inputs.parameters.cluster_id}} | grep {{inputs.parameters.name}} | awk '{print $5}')
            if [ "$SVC_STATUS" = "RUNNING" ]; then
              break
            elif [ "$SVC_STATUS" = "ERROR" ]; then
              exit 1
            fi

            if [ "$i" -ge "$threshold" ]; then
              echo "Timed out waiting for {{inputs.parameters.name}} to be ready."
              exit 1
            fi
            sleep 1m
          done

          echo $(tks appgroup list {{inputs.parameters.cluster_id}} | grep {{inputs.parameters.name}} | awk '{print $3}') | tee /mnt/out/svc_id.txt
      volumeMounts:
        - name: out
          mountPath: /mnt/out
    volumes:
      - name: out
        emptyDir: { }
    outputs:
      parameters:
      - name: svc_id
        valueFrom:
          default: "Something wrong"
          path: /mnt/out/svc_id.txt

  - name: delete-appgroup
    inputs:
      parameters:
      - name: cluster_id
      - name: name
      - name: appgroup_id
    container:
      name: delete-service
      image: harbor-cicd.taco-cat.xyz/tks/tks-e2e-test:test
      command:
        - /bin/bash
        - '-exc'
        - |
          tks login {{workflow.parameters.tks_api_url}} --organization-id master --account-id admin --password admin
          tks appgroup delete {{inputs.parameters.appgroup_id}}

          threshold=30
          for i in $(seq 1 $threshold)
          do
            SVC_EXIST=$(tks appgroup list {{inputs.parameters.cluster_id}} | grep {{inputs.parameters.appgroup_id}} | wc -l)
            if [ "$SVC_EXIST" = "0" ]; then
              break
            fi

            SVC_STATUS=$(tks appgroup list {{inputs.parameters.cluster_id}} | grep {{inputs.parameters.name}} | awk '{print $5}')
            if [ "$SVC_STATUS" = "DELETED" ]; then
              break
            elif [ "$SVC_STATUS" = "ERROR" ]; then
              exit 1
            fi

            if [ "$i" -ge "$threshold" ]; then
              echo "Timed out waiting for {{inputs.parameters.name}} to be deleted."
              exit 1
            fi
            sleep 1m
          done

  - name: get-appgroup-id
    inputs:
      parameters:
      - name: cluster_id
      - name: name
    container:
      name: get-appgroup-id
      image: harbor-cicd.taco-cat.xyz/tks/tks-e2e-test:test
      command:
        - /bin/bash
        - '-exc'
        - |
          tks login {{workflow.parameters.tks_api_url}} --organization-id master --account-id admin --password admin

          echo $(tks appgroup list {{inputs.parameters.cluster_id}} | grep {{inputs.parameters.name}} | awk '{print $3}') | tee /mnt/out/appgroup_id.txt
      volumeMounts:
        - name: out
          mountPath: /mnt/out
    volumes:
      - name: out
        emptyDir: { }
    outputs:
      parameters:
      - name: appgroup_id
        valueFrom:
          default: "Something wrong"
          path: /mnt/out/appgroup_id.txt
