apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-remove-servicemesh
  namespace: argo
spec:
  entrypoint: delete-start
  arguments:
    parameters:
      - name: site_name
        value: hanu-reference
      - name: iop_controlplane_name
        value: istio-controlplane
      - name: iop_gateway_name
        value: istio-ingress-gateway
      - name: revision
        value: 1-10-2
      - name: namespace
        value: istio-system
      - name: kube_version
        value: v1.18.6
  templates:
    - name: delete-start
      steps:
        - - name: delete-argocd-app
            template: delete-argocd-app
            arguments:
              parameters:
                - name: app_group
                  value: service-mesh
                - name: site_name
                  value: "{{workflow.parameters.site_name}}"
        - - name: delete-finalizer-app
            template: delete-finalizer-app
            arguments:
              parameters:
                - name: namespace
                  value: '{{workflow.parameters.namespace}}'
                - name: site_name
                  value: "{{workflow.parameters.site_name}}"
                - name: kubeconfig_secret_name
                  value: "{{workflow.parameters.site_name}}-kubeconfig"
        - - name: delete-kuberentes-gateway
            template: delete-kubernetes-resources
            arguments:
              parameters:
                - name: component_name
                  value: '{{workflow.parameters.iop_gateway_name}}'
                - name: component_type
                  value: gateway
                - name: kubeconfig_secret_name
                  value: "{{workflow.parameters.site_name}}-kubeconfig"
        - - name: delete-kubernetes-controlplane
            template: delete-kubernetes-resources
            arguments:
              parameters:
                - name: component_name
                  value: '{{workflow.parameters.iop_controlplane_name}}'
                - name: component_type
                  value: controlplane
                - name: kubeconfig_secret_name
                  value: "{{workflow.parameters.site_name}}-kubeconfig"
        - - name: delete-namespace
            template: delete-namespace
            arguments:
              parameters:
                - name: namespace
                  value: '{{workflow.parameters.namespace}}'
                - name: kubeconfig_secret_name
                  value: "{{workflow.parameters.site_name}}-kubeconfig"
    - name: delete-argocd-app
      inputs:
        parameters:
          - name: app_group
          - name: site_name
      container:
        name: delete-argocd-app
        image: docker.io/sktcloud/argocd-cli:v2.2.5
        command:
          - /bin/bash
          - '-c'
          - |
            function log() {
              level=$1
              msg=$2
              date=$(date '+%F %H:%M:%S')
              echo "[$date] $level     $msg"
            }
            ./argocd login $ARGO_SERVER --plaintext --insecure --username $ARGO_USERNAME \
            --password $ARGO_PASSWORD

            export ARGOCD_APP_NAME=$(echo "${SITE_NAME:0:8}")-service-mesh

            ./argocd app list -p $APP_NAME -l app=$ARGOCD_APP_NAME -o name | xargs ./argocd app delete -y
            log "INFO" "deleting argocd app"
        envFrom:
          - secretRef:
              name: decapod-argocd-config
        env:
          - name: APP_NAME
            value: "{{inputs.parameters.app_group}}"
          - name: SITE_NAME
            value: '{{inputs.parameters.site_name}}'
      activeDeadlineSeconds: 900
      retryStrategy:
        limit: 2
    - name: delete-finalizer-app
      inputs:
        parameters:
          - name: namespace
          - name: site_name
          - name: kubeconfig_secret_name
      container:
        name: delete-finalizer-app
        image: 'k8s.gcr.io/hyperkube:{{workflow.parameters.kube_version}}'
        command:
          - /bin/bash
          - '-c'
          - |
            function log() {
              level=$1
              msg=$2
              date=$(date '+%F %H:%M:%S')
              echo "[$date] $level     $msg"
            }

            APP_PREFIX=${SITE_NAME:0:8}
            cat <<< "$KUBE_CONFIG" > /etc/kubeconfig
            
            kubectl patch app $APP_PREFIX-servicemesh-kiali-resource -n argo --type merge -p '{"metadata":{"finalizers": [null]}}'
            kubectl patch app $APP_PREFIX-servicemesh-gateway -n argo --type merge -p '{"metadata":{"finalizers": [null]}}'
            kubectl patch app $APP_PREFIX-servicemesh-controlplane -n argo --type merge -p '{"metadata":{"finalizers": [null]}}'
            kubectl --kubeconfig=/etc/kubeconfig patch kialis kiali -n ${NAMESPACE} --type merge -p '{"metadata":{"finalizers": [null]}}'
            
            log "INFO" "argocd apps and kialis finalizers successfully deleted."
        env:
          - name: NAMESPACE
            value: '{{inputs.parameters.namespace}}'
          - name: SITE_NAME
            value: '{{inputs.parameters.site_name}}'
          - name: KUBE_CONFIG
            valueFrom:
              secretKeyRef:
                name: "{{ inputs.parameters.kubeconfig_secret_name }}"
                key: value
      activeDeadlineSeconds: 900
      retryStrategy:
        limit: 2
    - name: delete-kubernetes-resources
      inputs:
        parameters:
          - name: component_name
          - name: component_type
          - name: kubeconfig_secret_name
      container:
        name: delete-kubernetes-resources
        image: 'k8s.gcr.io/hyperkube:{{workflow.parameters.kube_version}}'
        command:
          - /bin/bash
          - '-c'
          - |
            function log() {
              level=$1
              msg=$2
              date=$(date '+%F %H:%M:%S')
              echo "[$date] $level     $msg"
            }

            function deleteGateway() {
              log "INFO" "deleteGateway() called!"
              log "INFO" "REVISION = [${REVISION}]"
              log "INFO" "COMPONENT_NAME = [${COMPONENT_NAME}]"
              log "INFO" "NAMESPACE = [${NAMESPACE}]"
              LABELS="istio.io/rev=${REVISION},operator.istio.io/component=IngressGateways"
              kubectl --kubeconfig=/etc/kubeconfig patch istiooperators ${COMPONENT_NAME}-${REVISION} -n ${NAMESPACE} --type merge -p '{"metadata":{"finalizers": [null]}}'
              kubectl --kubeconfig=/etc/kubeconfig delete istiooperators ${COMPONENT_NAME}-${REVISION} -n ${NAMESPACE}
              kubectl --kubeconfig=/etc/kubeconfig delete deployments -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete services -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete hpa -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete poddisruptionbudgets -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete serviceaccounts -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete rolebindings -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete roles -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete helmreleases service-mesh-gateway -n default
            }

            function deleteControlplane() {
              log "INFO" "deleteControlplane() called!"
              log "INFO" "REVISION = [${REVISION}]"
              log "INFO" "COMPONENT_NAME = [${COMPONENT_NAME}]"
              log "INFO" "NAMESPACE = [${NAMESPACE}]"
              LABELS="istio.io/rev=${REVISION},operator.istio.io/component=Pilot"
              kubectl --kubeconfig=/etc/kubeconfig patch istiooperators ${COMPONENT_NAME}-${REVISION} -n ${NAMESPACE} --type merge -p '{"metadata":{"finalizers": [null]}}'
              kubectl --kubeconfig=/etc/kubeconfig delete istiooperators ${COMPONENT_NAME}-${REVISION} -n ${NAMESPACE}
              kubectl --kubeconfig=/etc/kubeconfig delete deployments -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete services -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete hpa -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete configmaps -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete poddisruptionbudgets -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete envoyfilters -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete mutatingwebhookconfigurations -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete serviceaccounts -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete rolebindings -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete roles -n ${NAMESPACE} -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete clusterrolebindings -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete clusterroles -l ${LABELS}
              kubectl --kubeconfig=/etc/kubeconfig delete helmreleases service-mesh-controlplane -n default
            }

            cat <<< "$KUBE_CONFIG" > /etc/kubeconfig

            # delete Kubernetes resources
            if [[ ! -z "$COMPONENT_NAME" ]]; then
              if [[ ${COMPONENT_TYPE} =~ controlplane ]]; then
                log "INFO" "delete istio Controlplane"
                deleteControlplane
              elif [[ ${COMPONENT_TYPE} =~ gateway ]]; then
                log "INFO" "delete istio Gateway"
                deleteGateway
              else
                log "ERROR" "${COMPONENT_TYPE} does'nt exist."
                exit 1
              fi
            fi

            log "INFO" "${COMPONENT_NAME} successfully deleted."
        env:
          - name: COMPONENT_NAME
            value: '{{inputs.parameters.component_name}}'
          - name: COMPONENT_TYPE
            value: '{{inputs.parameters.component_type}}'
          - name: REVISION
            value: '{{workflow.parameters.revision}}'
          - name: NAMESPACE
            value: '{{workflow.parameters.namespace}}'
          - name: KUBE_CONFIG
            valueFrom:
              secretKeyRef:
                name: "{{ inputs.parameters.kubeconfig_secret_name }}"
                key: value
      activeDeadlineSeconds: 900
      retryStrategy:
        limit: 2
    - name: delete-namespace
      inputs:
        parameters:
          - name: namespace
          - name: kubeconfig_secret_name
      container:
        name: delete-namespace
        image: 'k8s.gcr.io/hyperkube:{{workflow.parameters.kube_version}}'
        command:
          - /bin/bash
          - '-c'
          - |
            function log() {
              level=$1
              msg=$2
              date=$(date '+%F %H:%M:%S')
              echo "[$date] $level     $msg"
            }

            cat <<< "$KUBE_CONFIG" > /etc/kubeconfig
            
            kubectl --kubeconfig=/etc/kubeconfig delete ns ${NAMESPACE}
            
            log "INFO" "${NAMESPACE} successfully deleted."
        env:
          - name: NAMESPACE
            value: '{{inputs.parameters.namespace}}'
          - name: KUBE_CONFIG
            valueFrom:
              secretKeyRef:
                name: "{{ inputs.parameters.kubeconfig_secret_name }}"
                key: value
      activeDeadlineSeconds: 900
      retryStrategy:
        limit: 2
