apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-install-ingress-controller
  namespace: argo
spec:
  entrypoint: deploy
  arguments:
    parameters:
    # Use cluster_id here
    - name: site_name
      value: "011b88fa-4d53-439f-9336-67845f994051"
    - name: manifest_repo_url
      value: ""
    - name: revision
      value: main
    - name: app_prefix
      value: "{{workflow.parameters.site_name}}"

  volumes:
  - name: config
    secret:
      secretName: tks-admin-kubeconfig-secret
  - name: artifacts
    configMap:
      name: aws-artifacts
      defaultMode: 0555

  templates:
  - name: deploy
    steps:

    - - name: install-ingress-controller
        templateRef:
          name: create-application
          template: installApps
        arguments:
          parameters:
          - name: list
            value: |
              [
                { "app_group": "tks-cluster-common", "path": "ingress-nginx", "namespace": "taco-system", "target_cluster": "" }
              ]
