apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-stack-delete-aws
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: tks_api_url
      value: "http://tks-api.tks.svc:9110"
    - name: cluster_id
      value: "czr9ts9ug"
    - name: organization_id
      value: "o1bm5xjim"

  templates:
  - name: main
    steps:
    - - name: call-get-appgroup-id-of-LMA
        templateRef:
          name: tks-cli
          template: get-appgroup-id
        arguments:
          parameters:
          - name: cluster_id
            value: "{{ workflow.parameters.cluster_id }}"
          - name: name
            value: "{{ workflow.parameters.cluster_id }}_lma"
    - - name: call-delete-appgroup-for-LMA
        templateRef:
          name: tks-cli
          template: delete-appgroup
        arguments:
          parameters:
          - name: cluster_id
            value: "{{ workflow.parameters.cluster_id }}"
          - name: name
            value: "{{ workflow.parameters.cluster_id }}_lma"
          - name: appgroup_id
            value: "{{steps.call-get-appgroup-id-of-LMA.outputs.parameters.appgroup_id}}"
    - - name: call-delete-usercluster
        templateRef:
          name: tks-cli
          template: delete-usercluster
        arguments:
          parameters:
          - name: cluster_id
            value: "{{ workflow.parameters.cluster_id }}"
          - name: organization_id
            value: "{{ workflow.parameters.organization_id }}"
