apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-stack-create-aws
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: tks_api_url
      value: "http://tks-api.tks.svc:9110"
    - name: cluster_name
      value: ""
    - name: description
      value: ""
    - name: organization_id
      value: "o1bm5xjim"
    - name: cloud_account_id
      value: "964d3631-2ea1-4bb0-b17e-03de91d6381b"
    - name: stack_template_id
      value: "aws-reference"
    - name: creator
      value: ""
    - name: infra_conf
      value: ""

  templates:
  - name: main
    steps:
    - - name: call-create-usercluster
        templateRef:
          name: tks-cli
          template: create-usercluster
        arguments:
          parameters:
          - name: cluster_name
            value: "{{workflow.parameters.cluster_name}}"
          - name: stack_template_id
            value: "{{workflow.parameters.stack_template_id}}"
          - name: organization_id
            value: "{{workflow.parameters.organization_id}}"
          - name: cloud_account_id
            value: "{{workflow.parameters.cloud_account_id}}"
          - name: creator
            value: "{{workflow.parameters.creator}}"
          - name: description
            value: "{{workflow.parameters.description}}"
          - name: infra_conf
            value: "{{workflow.parameters.infra_conf}}"

    - - name: call-create-appgroup-for-LMA
        templateRef:
          name: tks-cli
          template: create-appgroup
        arguments:
          parameters:
          - name: cluster_id
            value: "{{steps.call-create-usercluster.outputs.parameters.cluster-id}}"
          - name: name
            value: "{{steps.call-create-usercluster.outputs.parameters.cluster-id}}_lma"
          - name: type
            value: "LMA"            
          - name: creator
            value: "{{workflow.parameters.creator}}"
          - name: description
            value: "{{workflow.parameters.description}}"


