apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-create-contract-repo
  namespace: argo
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: contract_id
      value: "contract_uuid"
  templates:
  - name: createContractRepo
    activeDeadlineSeconds: 120
    container:
      name: 'createRepo'
      image: ghcr.io/sktelecom/ghcli-alpine:2.0.0
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -ecx
      - |
        echo $TOKEN | gh auth login --with-token
        echo "===== Current repo list ====="
        gh repo list openinfradev | grep tks-user-site
        gh repo list tks-management

        echo "===== Create and initialize tks-management/${CONTRACT_ID} site and manifests repositories ====="
        gh repo create tks-management/${CONTRACT_ID} --private --confirm

        cd ${CONTRACT_ID}
        echo -n ${TOKEN} | gh secret set API_TOKEN_GITHUB

        git clone https://$(echo -n $TOKEN)@github.com/openinfradev/tks-user-site-template
        cd tks-user-site-template
        git remote add new_contract https://$(echo -n $TOKEN)@github.com/tks-management/${CONTRACT_ID}
        git push new_contract main:main
        cd ..

      envFrom:
        - secretRef:
            name: "github-tks-mgmt-token"
      env:
        - name: CONTRACT_ID
          value: "{{workflow.parameters.contract_id}}"

  - name: main
    steps:
      - - name: createContractRepository
          template: createContractRepo
          arguments: {}

