apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tks-create-github-token-secret
  namespace: argo
spec:
  entrypoint: createTokenSecret
  arguments:
    parameters:
    - name: user
      value: "github_user"
    - name: token
      value: "github_token"
  templates:
  - name: createTokenSecret
    activeDeadlineSeconds: 120
    container:
      name: 'createClusterSite'
      image: 'k8s.gcr.io/hyperkube:v1.18.8'
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -ecx
      - |
        kubectl delete secret -n argo github-tks-mgmt-token || true
        kubectl create secret generic github-tks-mgmt-token --from-literal=USERNAME=${USER} --from-literal=TOKEN=${TOKEN} -n argo
      env:
      - name: USER
        value: "{{workflow.parameters.user}}"
      - name: TOKEN
        value: "{{workflow.parameters.token}}"
